controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_shoulder_ref_frame_joint
      - left_shoulder_1_flex_exte
      - left_shoulder_2_abdu_addu
      - left_shoulder_3_rotation
      - left_elbow_4_flex_exte
      - left_7_prona_supin
      - left_wrist_6_flex_exte
      - left_wrist_5_abdu_addu
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_shoulder_ref_frame_joint
      - right_shoulder_1_flex_exte
      - right_shoulder_2_abdu_addu
      - right_shoulder_3_rotation
      - right_elbow_4_flex_exte
      - right_7_prona_supin
      - right_wrist_6_flex_exte
      - right_wrist_5_abdu_addu