#!/usr/bin/env python

import numpy as np
import time
from math import pi, radians
import rospy
from robotiq_ft_sensor.msg import ft_sensor
import copy


class FTDataSave(object):

    def __init__(self):
        self.csv_data = []

        # Define CameraInfo subscriber
        rospy.Subscriber("robotiq_ft_sensor", ft_sensor, self.callback_ft)

    def callback_ft(self, msg):
        data_vec = [time.time(), msg.Fx, msg.Fy, msg.Fz, msg.Mx, msg.My, msg.Mz]
        self.csv_data.append(data_vec)

    def run(self):
        rospy.spin()

    def store_csv(self):
        data = copy.copy(self.csv_data)

        import pandas as pd
        import os
        # Create fields
        fields = ['ts', 'Fx', 'Fy', 'Fz', 'Mx', 'My', 'Mz']

        # Create pd dataframe
        df = pd.DataFrame(data=data, columns=fields)

        # Save df as csv
        csv_path = "/home/newdexterity/data/ft_recordings/ft_sensor.csv"
        if os.path.isfile(csv_path):
            print("File {} already exists.".format(csv_path))
            return
        df.to_csv(csv_path)

        # Log it
        rospy.loginfo("\nWritten data to: ./{}".format(csv_path))


if __name__ == '__main__':
    # Initialise node
    rospy.init_node('ft_recorder', anonymous=False)
    # Start tracker
    c = FTDataSave()
    rospy.on_shutdown(c.store_csv)
    c.run()
