#!/usr/bin/env python
from __future__ import print_function

import rospy
import moa_odrv_ros

if __name__ == '__main__':
    try:
        moa_odrv_ros.start_odrive()
    except rospy.ROSInterruptException:
        pass
